title: <p align="center"> Jue Wang </p>

logo: "/images/IMG_6582.JPG"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/jue-w-84463817/">Linkedin</a> |
  <a href="https://github.com/jwangprof">GitHub</a>
  </p>
  

theme: jekyll-theme-minimal
