title: "<p align='center'>Jue Wang</p>"
logo: "/images/unnamed.JPG"
description: |
  <p align='center'>
    <a href='https://www.linkedin.com/in/jue-w-84463817/'>Linkedin</a> |
    <a href='https://github.com/jwangprof'>GitHub</a>
  </p>
  <p align="justify">
    At the heart of my work is a passion for using analytics to drive business decisions and foster operational excellence.
    I love collaborating on projects that challenge me to think creatively and push the boundaries of what's possible with data.
    <br><br>
    When I'm not crunching numbers, you might find me scuba diving into ocean conservation projects or exploring new hiking trails.
    <br><br>
    Let’s connect and make data work for us!
    <br><br>
  </p>

theme: jekyll-theme-minimal
