title: "<p align='center'>Jue Wang</p>"
logo: "/images/IMG_6582.JPG"
description:
  "<p align='center'>
    <a href='https://www.linkedin.com/in/jue-w-84463817/'>Linkedin</a> |
    <a href='https://github.com/jwangprof'>GitHub</a>
  </p>"

bio:
  greeting: "👋 Hi there! I'm Jue,"
  passion: "At the heart of my work is a passion for using analytics to drive business decisions and foster operational excellence."
  collaboration: "I love collaborating on projects that challenge me to think creatively and push the boundaries of what's possible with data."
  hobbies: "When I'm not crunching numbers, you might find me scuba diving into ocean conservation projects or exploring new hiking trails."
  invitation: "Let’s connect and make data work for us!"

theme: jekyll-theme-minimal
